export const BELTS = [
  "Undisputed WWE Champion",
  "World Heavyweight Champion",
  "Women's World Champion",
  "WWE Women’s Champion",
  "Intercontinental Champion",
  "United States Champion",
  "World Tag Team Champions",
  "SmackDown Tag Team Champions",
  "WWE Women's Tag Team Champions",
  "NXT Champion",
  "NXT Women's Champion",
  "NXT North American Champion",
  "NXT Tag Team Champions",
  "NXT Heritage Cup Champion",
];

export const CHAMPIONS = [
  "Cody Rhodes",
  "Damian Priest",
  "Becky Lynch",
  "Bayley",
  "Sami Zayn",
  "Logan Paul",
  "Awesome Truth",
  "A-Town Down Under",
  "The Kabuki Warriors",
  "Ilja Dragunov",
  "Roxanne Perez",
  "Oba Femi",
  "Nathan Frazer & Axiom",
  "Charlie Dempsey",
];
